title: <p align="center"> Tshimologo Molefyane </p>

logo: "/images/coverpage.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tshimologo-molefyane247/">LinkedIn</a> |
  <a href="https://github.com/TshimologoM">GitHub</a>
  </p>
  
  <p align="justify">
  -I completed an M.S. in electronic engineering and computer science degree from NKUST, Taiwan.
  <br>
  -I hold a B.S in mathematical statistics from the University of Pretoria in South Africa.
  <br>
  -I am a data scientist with a focus on Machine learning using Python and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-71F72Y0L8G # Google Analytics tracking ID
